language: java
dist: bionic
addons:
  apt:
    sources:
      - ppa:chris-lea/redis-server
    packages:
    - redis-tools
    - redis-server
jdk:
  - oraclejdk9
  - oraclejdk11
  - openjdk9
services:
  - mysql
  - redis
  
